feat(01-building-blocks}: change from fail to not fail

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -13,7 +13,9 @@ jobs:
     steps:
       - name: Failed step
         run: |
-            echo "I will fail"
-            exit 1
+            # echo "I will fail"
+            # exit 1
+            echo "I will not fail"
+            exit 0
       - name: Say goodbye
         run: echo "GoodBye"
